# Generated by Django 5.0.7 on 2024-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTicket', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_whatsapp',
            field=models.CharField(max_length=10),
        ),
    ]
